print('\nDobro, Triplo e Raiz Quadrada\n')
n = int(input('Digite um número: '))
print('\nO Dobro de {} é {}'.format(n, (2 * n)))
print('O Triplo de {} é {}'.format(n, (3 * n)))
print('E a Raiz Quadrada de {} é {:.2f}'.format(n, (n ** (1/2))))
