x = input('Digite algo: ')

print('O tipo primitivo desse valor é {}'.format(type(x)))
print('Só tem espaços? {}'.format(x.isspace()))
print('É um número? {}'.format(x.isnumeric()))
print('É totalmente alfabético? {}'.format(x.isalpha()))
print('É alfanumérico? {}'.format(x.isalnum()))
print('Está todo em maiúsculas? {}'.format(x.isupper()))
print('Está todo em minúsculas? {}'.format(x.islower()))
print('Está capitalizada? {}'.format(x.istitle()))
